import type { Metadata } from "next";
import { Lato } from "next/font/google";
import { Providers } from "../components/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const lato = Lato({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={lato.className}>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
